name: Setup CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: uptime
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: readme
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: site
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: graphs
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: response-time
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: summary
